language: python
python:
  - "3.8"
before_install:
  - mv dummy_secrets.yaml secrets.yaml
  - mv dummy_service_account.json service_account.json
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config