- id: '1579368286267'
  alias: Turn outdoor lights off
  description: ''
  trigger:
  - at: '23:35:00'
    platform: time
  condition: []
  action:
  - service: light.turn_off
    target:
      device_id: cface4cdb90d68175e3a8dcb4f5dcf45
      entity_id: light.back_door_porch
    data: {}
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.house_light_up_time
- id: '1579910576936'
  alias: Living room light off
  description: ''
  trigger:
  - at: '23:30:00'
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.livingroomlight
      - switch.livingroom3
      - switch.kitchen_floor_light
  mode: single
- id: '1581724986134'
  alias: Heating on
  description: Turn all heating on from 5 mins after sunset if its cold outside
  trigger:
  - platform: numeric_state
    entity_id: weather.home
    attribute: temperature
    below: 12
  - platform: sun
    event: sunset
    offset: 00:05:00
  condition:
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: weather.home
      attribute: temperature
      below: 12
    - condition: sun
      after: sunset
    - condition: numeric_state
      entity_id: climate.downstairs_living_room
      attribute: current_temperature
      below: 20
  - condition: time
    before: '22:30:00'
    after: 00:00:00
  action:
  - data:
      temperature: 20
    service: climate.set_temperature
    target:
      entity_id: climate.downstairs_living_room
  - data:
      temperature: 19
    service: climate.set_temperature
    target:
      entity_id:
      - climate.upstairs_master_bedroom
      - climate.upstairs_study
  mode: single
- id: '1581725082327'
  alias: Upstairs Off
  description: Turn off heating upstairs at 18:45
  trigger:
  - at: '18:45:00'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    service: climate.set_temperature
    target:
      entity_id:
      - climate.upstairs_master_bedroom
      - climate.upstairs_study
  mode: single
- id: '1581725156741'
  alias: Nightly Heating Power Down
  description: Turn off anything heating related at 22:30
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    service: climate.set_temperature
    target:
      entity_id:
      - climate.downstairs_living_room
      - climate.upstairs_study
      - climate.upstairs_master_bedroom
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: switch.hotwater
  mode: single
- id: '1581803790658'
  alias: Landing Light off at 23:45
  description: ''
  trigger:
  - at: '23:45:00'
    platform: time
  condition: []
  action:
  - service: light.turn_off
    target:
      device_id: 8dd3b302d420f1394f0c1a4b31200497
  mode: single
- id: '1581804716802'
  alias: Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: script.1581804598858
    service: script.turn_on
- id: '1586039347252'
  alias: Landing Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    platform: state
    to: 'on'
    from: 'off'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '23:45:00'
    - condition: sun
      before: sunrise
  action:
  - service: light.turn_on
    target:
      device_id: 8dd3b302d420f1394f0c1a4b31200497
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.landing_motion
  mode: restart
- id: '1586113907411'
  alias: Reset PIR
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: E6BC6Eoff
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1586113907412'
  alias: Reset Shed Door Sensor
  description: ''
  trigger:
  - entity_id: binary_sensor.shed_door_sensor
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 986BA9off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
  mode: single
- id: '1607031963787'
  alias: Security Alarm Tag is Scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 8d9f1d71-b7c4-4659-bc05-138cb1236295
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.home
  mode: single
- id: '1608424917760'
  alias: Hot Water in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: script.boost_hot_water
    data: {}
  mode: single
- id: '1611338137506'
  alias: Hot Water at 16:30
  description: ''
  trigger:
  - platform: time
    at: '16:30'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.hotwater_2
  mode: single
- id: '1612026197579'
  alias: Landing lights off after motion
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.landing_motion
  condition: []
  action:
  - service: light.turn_off
    target:
      device_id: 8dd3b302d420f1394f0c1a4b31200497
  mode: single
- id: '1612027339078'
  alias: Turn off heating after boost
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.heating_boost
  condition: []
  action:
  - service: climate.set_temperature
    target:
      entity_id: climate.downstairs_living_room
    data:
      temperature: 7
  mode: single
- id: '1637008787311'
  alias: Freya's Remote
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e2001_e2002.yaml
    input:
      integration: deCONZ
      controller_device: 6ea6c0b214b7622c5d068f368292f20d
      helper_last_controller_event: input_text.freya_controller
      action_button_left_short:
      - type: turn_on
        device_id: 600ecb283ab949bf9b1b745403e28974
        entity_id: light.extended_color_light_3
        domain: light
      action_button_right_short:
      - type: turn_off
        device_id: 600ecb283ab949bf9b1b745403e28974
        entity_id: light.extended_color_light_3
        domain: light
      action_button_up_short:
      - device_id: 600ecb283ab949bf9b1b745403e28974
        domain: light
        entity_id: light.extended_color_light_3
        type: brightness_increase
      action_button_down_short:
      - device_id: 600ecb283ab949bf9b1b745403e28974
        domain: light
        entity_id: light.extended_color_light_3
        type: brightness_decrease
- id: '1637014229376'
  alias: Study Controller
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: deCONZ
      controller_device: 999d5983438a25da9f6a81b87421da57
      helper_last_controller_event: input_text.study_controller
      action_button_center_short:
      - type: toggle
        device_id: dbb60cf9c35969d0ac5a6caacc3894eb
        entity_id: light.study
        domain: light
- id: '1639933719355'
  alias: Freya's Controller
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: deCONZ
      action_button_center_short: []
      controller_device: 999d5983438a25da9f6a81b87421da57
      helper_last_controller_event: input_text.freya_controller
      action_button_up_short: []
      action_button_down_short: []
      action_button_right_short: []
- id: '1639935890913'
  alias: Study Remote
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e2001_e2002.yaml
    input:
      integration: deCONZ
      controller_device: 6ea6c0b214b7622c5d068f368292f20d
      helper_last_controller_event: input_text.study_controller
      action_button_up_short:
      - service: light.turn_on
        target:
          entity_id: light.study
      action_button_up_release:
      - service: light.turn_on
        target:
          entity_id: light.study
      action_button_left_short: []
      action_button_down_short:
      - service: light.turn_off
        target:
          entity_id: light.study
      action_button_down_release:
      - service: light.turn_off
        target:
          entity_id: light.study
      action_button_up_double:
      - service: light.turn_on
        target:
          entity_id: light.study
- id: '1640031148188'
  alias: Reset things on restart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      payload: E6BC6Eoff
      topic: tele/rfbridge/RESULT
  mode: single
- id: '1641422941749'
  alias: Manual Upstairs Heating Boost
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.manual_floor_1_switch
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: climate.set_temperature
    target:
      entity_id:
      - climate.upstairs_study
      - climate.upstairs_master_bedroom
    data:
      temperature: 21.5
  mode: single
- id: '1641751162690'
  alias: Study Lights
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: deCONZ
      controller_device: 7c33ffc006503a92362d66511db95509
      helper_last_controller_event: input_text.new_study_controller
      action_button_center_short:
      - service: light.toggle
        target:
          device_id:
          - 49aef742c747f12a3e8c7946b5f3c7b4
          - dbb60cf9c35969d0ac5a6caacc3894eb
      action_button_left_short:
      - service: light.turn_on
        target:
          device_id: 49aef742c747f12a3e8c7946b5f3c7b4
        data_template:
          hs_color:
          - '{{ (30 + (state_attr(''light.shellyrgbw2_a8e75d'', ''hs_color'')[0] or
            0)) % 360 }}'
          - 100
          brightness_pct: 100
          transition: 1
      action_button_right_short:
      - service: light.turn_on
        target:
          device_id: 49aef742c747f12a3e8c7946b5f3c7b4
        data_template:
          hs_color:
          - '{{ ((state_attr(''light.shellyrgbw2_a8e75d'', ''hs_color'')[0] or 30)
            - 30) % 360 }}'
          - 100
          brightness_pct: 100
          transition: 1
      action_button_center_long: []
      action_button_center_double:
      - service: light.turn_off
        target:
          device_id: dbb60cf9c35969d0ac5a6caacc3894eb
      button_center_double_press: true
      action_button_down_short:
      - service: light.turn_off
        target:
          device_id: 49aef742c747f12a3e8c7946b5f3c7b4
      action_button_up_short:
      - service: light.turn_on
        target:
          device_id: 49aef742c747f12a3e8c7946b5f3c7b4
- id: '1642377899412'
  alias: Turn off hot water after boost
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hotwater_boost
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.hotwater
  mode: single
- id: '1644091533856'
  alias: Security Lights at night
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_front_of_house
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.side_door_wc
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.motion_g3_flex
    from: 'off'
    to: 'on'
    enabled: false
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
    for:
      hours: 0
      minutes: 20
      seconds: 0
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.front_door_light
      - light.back_door_security
      - light.side_door_security
  - service: timer.start
    data:
      duration: '0'
    target:
      entity_id: timer.outdoor_motion
  mode: single
- id: '1644092087858'
  alias: Reset security light
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.outdoor_motion
  condition: []
  action:
  - service: script.turn_off_outdoor_security_lights
    data: {}
  mode: single
- id: '1644096668891'
  alias: test scene
  description: ''
  trigger: []
  condition: []
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.study_lights_on
  mode: single
- id: '1663882381865'
  alias: Blinds up in the morning
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:15:00
  condition: []
  action:
  - service: script.sitting_room_blind_half_height
    data: {}
  - service: script.kitchen_blinds_up
    data: {}
  mode: single
- id: '1664030408335'
  alias: Davin's Controller
  description: ''
  use_blueprint:
    path: EPMatt/ikea_e1524_e1810.yaml
    input:
      integration: deCONZ
      helper_last_controller_event: input_text.davin_controller
      controller_device: ccf30eb5e997f830f44067242a9ce49b
      action_button_left_short: []
- id: '1664030585857'
  alias: Davin's Hook
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      light: light.color_light_3
      controller_device: ccf30eb5e997f830f44067242a9ce49b
      controller_model: IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote
      on_brightness: 255
      min_brightness: 79
      force_brightness: true
- id: '1664031869383'
  alias: Freya's Hook
  description: ''
  use_blueprint:
    path: EPMatt/light.yaml
    input:
      controller_device: 999d5983438a25da9f6a81b87421da57
      controller_model: IKEA E1524/E1810 TRÅDFRI Wireless 5-Button Remote
      light: light.extended_color_light_3
      on_brightness: 200
      force_brightness: true
- id: '1664032148317'
  alias: Turn off Davin's light on a school day
  description: ''
  trigger:
  - platform: time
    at: 08:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    before: 00:00:00
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.color_light_3
  mode: single
