- id: '1579368086048'
  alias: Outdoor lights on at Sunset
  description: ''
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.pathwaylights
    service: switch.turn_on
- id: '1579368286267'
  alias: Turn outdoor lights off
  description: ''
  trigger:
  - at: '23:35'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.outdoor
    service: switch.turn_off
  - data: {}
    entity_id: switch.internalpathway
    service: switch.turn_off
  - data: {}
    entity_id: switch.pathlights
    service: switch.turn_off
- id: '1579910205699'
  alias: Living room light on at dusk
  description: ''
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.living_room_light
    service: switch.turn_on
- id: '1579910576936'
  alias: Living room light off
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - entity_id: switch.livingroomlight
    service: switch.turn_off
  - delay: 00:15:00
  - service: switch.turn_off
    data: {}
    entity_id: switch.livingroom2
  mode: single
- id: '1581724986134'
  alias: Heating on
  description: Turn all heating on from 15 mins after sunset.
  trigger:
  - platform: sun
    event: sunset
    offset: +00:15:00
  condition: []
  action:
  - data:
      temperature: 21.5
    entity_id: climate.downstairs_living_room
    service: climate.set_temperature
  - data:
      temperature: 17
    entity_id: climate.upstairs_master_bedroom
    service: climate.set_temperature
  - type: turn_on
    device_id: cface4cdb90d68175e3a8dcb4f5dcf45
    entity_id: switch.hotwater_2
    domain: switch
  mode: single
- id: '1581725082327'
  alias: Upstairs Off
  description: Turn off heating upstairs at 18:45
  trigger:
  - at: '18:45'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    entity_id: climate.upstairs_master_bedroom
    service: climate.set_temperature
  mode: single
- id: '1581725156741'
  alias: Downstairs Heating Off
  description: Turn Downstairs heating off at 22:30
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    entity_id: climate.downstairs_living_room
    service: climate.set_temperature
  mode: single
- id: '1581803790658'
  alias: Landing Light off at 23:45
  description: ''
  trigger:
  - at: '23:45'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: light.shellydimmer2_d8bfc019cb69
    service: light.turn_off
  mode: single
- id: '1581804716802'
  alias: Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: script.1581804598858
    service: script.turn_on
- id: '1586039347252'
  alias: Landing Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    platform: state
    to: 'on'
    from: 'off'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '23:45'
    - condition: sun
      before: sunrise
  action:
  - service: light.turn_on
    data:
      brightness_pct: 30
    entity_id: light.shellydimmer2_d8bfc019cb69
  - delay: 00:05:00
  - service: light.turn_off
    data: {}
    entity_id: light.shellydimmer2_d8bfc019cb69
  mode: restart
- id: '1586113907411'
  alias: Reset PIR
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: E6BC6Eoff
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1586113907412'
  alias: Reset Shed Door Sensor
  description: ''
  trigger:
  - entity_id: binary_sensor.shed_door_sensor
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 986BA9off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
  mode: single
- id: '1587913331545'
  alias: Reset Smoke Alarm
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      payload: 649606off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1588437919449'
  alias: Toggle Playroom Light
  description: ''
  trigger:
  - entity_id: binary_sensor.playroom_rf_light_switch
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - entity_id: switch.playroom_light
    service: switch.toggle
  - delay: 00:00:02
  - service: mqtt.publish
    data:
      payload: 84A794off
      topic: tele/rfbridge/RESULT
  mode: single
- id: '1590162517183'
  alias: Toggle Pathway
  description: ''
  trigger:
  - entity_id: switch.pathway
    platform: state
  condition: []
  action:
  - data: {}
    entity_id: switch.pathlights
    service: switch.toggle
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /6
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
- id: '1606991349298'
  alias: Tag tester is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: d6d576ea-7f31-4698-8ace-7c451cd085c3
  condition: []
  action:
  - type: toggle
    device_id: 157d5e14767e47a58d7894e7ee228828
    entity_id: switch.studylight
    domain: switch
  mode: single
- id: '1607031963787'
  alias: Tag Kitchen Timer is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 4be40cb9-9645-4cb9-9e67-43ad0ec56f56
  condition: []
  action:
  - service: script.simple_timer
    data: {}
  mode: single
- id: '1608424917760'
  alias: Hot Water in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition: []
  action:
  - service: script.boost_hot_water
    data: {}
  mode: single
