- id: '1579368086048'
  alias: Outdoor lights on at Sunset
  description: ''
  trigger:
  - event: sunset
    offset: +00:15:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.pathwaylights
    service: switch.turn_on
- id: '1579368286267'
  alias: Turn outdoor lights off
  description: ''
  trigger:
  - at: '23:35'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.outdoor
    service: switch.turn_off
  - data: {}
    entity_id: switch.pathwaylights
    service: switch.turn_off
  - data: {}
    entity_id: switch.pathway
    service: switch.turn_off
- id: '1579910205699'
  alias: Living room light on at dusk
  description: ''
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.living_room_light
    service: switch.turn_on
- id: '1579910576936'
  alias: Living room light off
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - entity_id: switch.living_room_light
    service: switch.turn_off
- id: '1581724986134'
  alias: Downstairs Heating on
  description: Turn downstairs on for from 17:45
  trigger:
  - at: '17:45'
    platform: time
  condition: []
  action:
  - data:
      temperature: 21
    entity_id: climate.downstairs_heating
    service: climate.set_temperature
  - data:
      temperature: 20
    entity_id: climate.upstairs_heating
    service: climate.set_temperature
- id: '1581725082327'
  alias: Upstairs Off
  description: Turn off heating upstairs at 19:00
  trigger:
  - at: '19:00'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    entity_id: climate.upstairs_heating
    service: climate.set_temperature
- id: '1581725156741'
  alias: Downstairs Heating Off
  description: Turn Downstairs heating off at 22:30
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - data:
      temperature: 7
    entity_id: climate.downstairs_heating
    service: climate.set_temperature
- id: '1581803658819'
  alias: Landing Light on at Dusk
  description: As the above!
  trigger:
  - event: sunset
    offset: +00:10:00
    platform: sun
  condition: []
  action:
  - data: {}
    entity_id: switch.landinglight
    service: switch.turn_on
- id: '1581803790658'
  alias: Landing Light off at 23:45
  description: ''
  trigger:
  - at: '23:45'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.landinglight
    service: switch.turn_off
- id: '1581804716802'
  alias: Lights On
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: script.1581804598858
    service: script.turn_on
- id: '1581807159917'
  alias: Hot Water Boost
  description: Turn on hot water for 1 hour
  trigger: []
  condition: []
  action:
  - data:
      time_period: 01:00:00
    entity_id: water_heater.hot_water
    service: hive.boost_hot_water
- id: '1586039347252'
  alias: Landing Motion
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.landinglight
      state: 'off'
    - condition: or
      conditions:
      - after: '23:45:00'
        condition: time
      - before: sunrise
        condition: sun
  action:
  - data: {}
    entity_id: switch.landinglight
    service: switch.turn_on
- id: '1586113907411'
  alias: Reset PIR
  description: ''
  trigger:
  - entity_id: binary_sensor.pir_motion
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: E6BC6Eoff
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1586113907412'
  alias: Reset Test Sensor
  description: ''
  trigger:
  - entity_id: binary_sensor.test_sonoff_sensor
    for: 0:00:15
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 986BA9off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1586116736096'
  alias: Landing Light Off After 5 mins
  description: If it's after lights off, turn light on for 5 mins if movement upstairs
  trigger:
  - entity_id: binary_sensor.pir_motion
    for: 0:05:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '23:45:00'
    before: 06:00:00
    condition: time
  action:
  - data: {}
    entity_id: switch.landinglight
    service: switch.turn_off
- id: '1587913331545'
  alias: Reset Smoke Alarm
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      payload: 649606off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1588437919449'
  alias: Toggle Playroom Light
  description: ''
  trigger:
  - entity_id: binary_sensor.playroom_rf_light_switch
    platform: state
  condition: []
  action:
  - entity_id: switch.playroom_light
    service: switch.toggle
  - data:
      payload: 84A794off
      topic: tele/rfbridge/RESULT
    service: mqtt.publish
- id: '1590162517183'
  alias: Toggle Pathway
  description: ''
  trigger:
  - entity_id: switch.pathway
    platform: state
  condition: []
  action:
  - data: {}
    entity_id: switch.pathwaylights
    service: switch.toggle

- id: shellies_announce
  alias: 'Shellies Announce'
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/6"
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

- id: 'shellies_discovery'
  alias: 'Shellies Discovery'
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'

