---
- platform: generic_thermostat
  name: Downstairs (Living Room)
  min_temp: 5
  max_temp: 32
  cold_tolerance: 0.3
  hot_tolerance: 0
  initial_hvac_mode: "heat"
  heater: switch.downstairs_living_room
  target_sensor: sensor.living_room_temperature
  target_temp: 7
- platform: generic_thermostat
  name: Downstairs (Kitchen)
  min_temp: 5
  max_temp: 30
  cold_tolerance: 0.3
  hot_tolerance: 0
  initial_hvac_mode: "heat"
  heater: switch.downstairs_kitchen
  target_sensor: sensor.kitchen_temperature
  target_temp: 7
- platform: generic_thermostat
  name: Upstairs (Study)
  min_temp: 5
  max_temp: 30
  cold_tolerance: 0.3
  hot_tolerance: 0
  initial_hvac_mode: "heat"
  heater: switch.floor1
  target_sensor: sensor.office_temperature
  target_temp: 7
- platform: generic_thermostat
  name: Upstairs (Master Bedroom)
  min_temp: 5
  max_temp: 30
  cold_tolerance: 0.3
  hot_tolerance: 0
  initial_hvac_mode: "heat"
  heater: switch.floor2
  target_sensor: sensor.master_bedroom_temperature_2
  target_temp: 7
