# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies:    
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes   

stream:

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url

  

sensor:
  - platform: integration
    source: sensor.gas_usage
    name: gas_used
    method: left
    round: 2

google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
   - camera
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate

timer:
  landing_motion:
    duration: '00:03:00'
  outdoor_motion:
    duration: '00:03:00'
  hotwater_boost:
    duration: '01:00:00'
  heating_boost:
    duration: '01:00:00'
  pantry_light_timer:
    duration: '00:10:00'

 
media_player:
  - platform: enigma2
    host: 192.168.1.131
    password: !secret vu_password




homeassistant:
  customize: !include customize.yaml

template: !include_dir_merge_list template
mqtt: !include_dir_merge_list mqtt

switch: !include switches.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml