# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies:    
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes   

stream:
wake_on_lan: 

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url

utility_meter:
  energy:
    name: House Smart Mains Meter
    source: sensor.shellyem_c7faf3_channel_2_energy
    tariffs:
      - peak
      - offpeak
      - night
      - weekend

schedule:
  electricity_peak:
    name: "Peak Electrcity Times"
    monday:
      - from: "17:00:00"
        to: "19:00:00"
    tuesday:
      - from: "17:00:00"
        to: "19:00:00"
    wednesday:
      - from: "17:00:00"
        to: "19:00:00"
    thursday:
      - from: "17:00:00"
        to: "19:00:00"
    friday:
      - from: "17:00:00"
        to: "19:00:00"
  electricity_offpeak:
    name: "Off Peak Electricity Times"
    monday:
      - from: "08:00:00"
        to: "17:00:00"
      - from: "19:00:00"
        to: "23:00:00"
    tuesday:
      - from: "08:00:00"
        to: "17:00:00"
      - from: "19:00:00"
        to: "23:00:00"
    wednesday:
      - from: "08:00:00"
        to: "17:00:00"
      - from: "19:00:00"
        to: "23:00:00"
    thursday:
      - from: "08:00:00"
        to: "17:00:00"
      - from: "19:00:00"
        to: "23:00:00"
    friday:
      - from: "08:00:00"
        to: "17:00:00"
      - from: "19:00:00"
        to: "23:00:00"
  electricity_night:
    name: "Nighttime Electrcity Times"
    monday:
      - from: "23:00:00"
        to: "24:00:00"
    tuesday:
      - from: "00:00:00"
        to: "08:00:00"
      - from: "23:00:00"
        to: "24:00:00"
    wednesday:
      - from: "00:00:00"
        to: "08:00:00"
      - from: "23:00:00"
        to: "24:00:00"
    thursday:
      - from: "00:00:00"
        to: "08:00:00"
      - from: "23:00:00"
        to: "24:00:00"
    friday:
      - from: "00:00:00"
        to: "08:00:00"
      - from: "23:00:00"
        to: "24:00:00"
  electricity_weekend:
    name: "Weekend Electrcity Times"
    saturday:
      - from: "08:00:00"
        to: "24:00:00"
    sunday:
      - from: "00:00:00"
        to: "24:00:00"     
    monday:
      - from: "00:00:00"
        to: "08:00:00"
  
sensor:
  - platform: integration
    source: sensor.gas_usage
    name: gas_used
    method: left
    round: 2
  - platform: worldtidesinfo
    api_key: 122f5c26-a9be-4184-942a-cde314ce4cc9


google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
   - camera
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate

timer:
  landing_motion:
    duration: '00:03:00'
  outdoor_motion:
    duration: '00:03:00'
  hotwater_boost:
    duration: '01:00:00'
  heating_boost:
    duration: '01:00:00'
  pantry_light_timer:
    duration: '00:10:00'

 
# media_player:
#   - platform: enigma2
#     name: Satellite & Saroview Receiver
#     host: 192.168.1.131
#     mac_address: 00:1d:ec:0e:5f:01
#     deep_standby: true
#     password: !secret vu_password

homeassistant:
  customize: !include customize.yaml

template: !include_dir_merge_list template
mqtt: !include_dir_merge_list mqtt

switch: !include switches.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml