
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

frontend:
  themes: !include_dir_merge_named themes   

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin
    password: !secret router_password

tplink:
  discovery: false
  light:
    - host: 192.168.1.141

# Text to speech
tts:
  - platform: google_translate

hive:
  username: adrian.skehill@gmail.com
  password: !secret hive_password

switch:
  - platform: wake_on_lan
    mac: a4:83:e7:97:53:c0

media_player:
  - platform: androidtv
    name: Philips OLED
    host: 192.168.1.145
  - platform: braviatv
    name: Playroom TV
    host: 192.168.1.111

spotify:
  client_id: 2e4914baee3c4576ba89393016fb588c
  client_secret: !secret spotify_secret

binary_sensor:
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Pir Motion'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: 'E6BC6E'
      payload_off: 'E6BC6Eoff'
      device_class: motion
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Upstairs Smoke Alarm'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '649606'
      payload_off: '649606off'
      device_class: smoke
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: "Playroom RF Light Switch"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '84A794'
      payload_off: '84A794off'
    
homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
