
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

frontend:
  themes: !include_dir_merge_named themes   


tplink:
  discovery: false
  light:
    - host: 192.168.1.141

google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate


timer:
  bread:
    duration: '00:01:00'
  stew:
    duration: '00:02:30'

switch:
  - platform: template
    switches:
      upstairstemplate:
        friendly_name: "Upstairs Template"
        value_template: "{{ is_state('switch.upstairs', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.hotwater_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.hotwater_2
      downstairstemplate:
        friendly_name: "Downstairs Template"
        value_template: "{{ is_state('switch.downstairs', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.hotwater_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.hotwater_2
      testtemplate:
        friendly_name: "Test Template"
        value_template: "{{ is_state('switch.livingroom2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.livingroomlight
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.livingroomlight
  - platform: wake_on_lan
    mac: a4:83:e7:97:53:c0

# nest:
#   client_id:  476574656894-0q443uj6rpflnq8tm9u4f7fa1gsuh3or.apps.googleusercontent.com 
#   client_secret:  FLw_m9GzoeMt_80WmtXZHdqF 
#   # "Project ID" in the Device Access Console
#   project_id: nestdoorbell
#   # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
#   subscriber_id: projects/project-label-22ee1/subscriptions/SUBSCRIBER_ID

climate:
  - platform: generic_thermostat
    name: Upstairs (Master Bedroom)
    min_temp: 5
    max_temp: 32
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: group.upstairs_heating
    target_sensor: sensor.shelly_h_t_1a9705_temperature
    keep_alive: 
      minutes: 5
    target_temp: 7
  - platform: generic_thermostat
    name: Downstairs (Living Room)
    min_temp: 5
    max_temp: 32
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: group.downstairs_heating
    target_sensor: sensor.shelly_h_t_9551e9_temperature
    keep_alive: 
      minutes: 5
    target_temp: 7


media_player:
  - platform: androidtv
    name: Philips OLED
    host: 192.168.1.145
  - platform: braviatv
    name: Playroom TV
    host: 192.168.1.111
  - platform: enigma2
    host: vuduo2.lan
    password: !secret vu_password

spotify:
  client_id: 2e4914baee3c4576ba89393016fb588c
  client_secret: !secret spotify_secret

binary_sensor:
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Pir Motion'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: 'E6BC6E'
      payload_off: 'E6BC6Eoff'
      device_class: motion
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Upstairs Smoke Alarm'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '649606'
      payload_off: '649606off'
      device_class: smoke
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: "Playroom RF Light Switch"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '84A794'
      payload_off: '84A794off'
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: "Shed Door Sensor"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '986BA9' 
      payload_off: '986BA9off'

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
