
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies:    
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes   

stream:

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url



tplink:
  discovery: false
  light:
    - host: 192.168.1.141

google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate


timer:
  landing_motion:
    duration: '00:06:00'
  hotwater_boost:
    duration: '01:00:00'
  heating_boost:
    duration: '01:00:00'
  bread:
    duration: '00:01:00'
  stew:
    duration: '00:02:30'

switch:
  - platform: template
    switches:
      upstairstemplate:
        friendly_name: "Upstairs Template"
        value_template: "{{ is_state('switch.upstairs', 'on') and is_state('switch.hotwater', 'on')}}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id:
            - switch.hotwater
            - switch.upstairs
        turn_off:
          service: switch.turn_off
          data:
            entity_id: 
            - switch.upstairs
      downstairstemplate:
        friendly_name: "Downstairs Template"
        value_template: "{{ is_state('switch.downstairs', 'on') and is_state('switch.hotwater', 'on')}}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: 
            - switch.hotwater
            - switch.downstairs
        turn_off:
          service: switch.turn_off
          data:
            entity_id: 
            - switch.downstairs
  - platform: wake_on_lan
    mac: a4:83:e7:97:53:c0

climate:
  - platform: generic_thermostat
    name: Upstairs (Study)
    min_temp: 5
    max_temp: 32
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.upstairstemplate
    keep_alive:
      minutes: 5
    target_sensor: sensor.shelly_h_t_1a9705_temperature
    target_temp: 7
  - platform: generic_thermostat
    name: Downstairs (Living Room)
    min_temp: 5
    max_temp: 32
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.downstairstemplate 
    keep_alive:
      minutes: 5
    target_sensor: sensor.shelly_h_t_9551e9_temperature
    target_temp: 7
 

media_player:
  - platform: androidtv
    name: Philips OLED
    host: 192.168.1.128
  - platform: braviatv
    name: Playroom TV
    host: 192.168.1.111
  - platform: enigma2
    host: 192.168.1.131
    password: !secret vu_password

spotify:
  client_id: 2e4914baee3c4576ba89393016fb588c
  client_secret: !secret spotify_secret

sensor:
  - platform: template
    sensors:
      nextsunrise:
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down

binary_sensor:
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Pir Motion'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: 'E6BC6E'
      payload_off: 'E6BC6Eoff'
      device_class: motion
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: 'Upstairs Smoke Alarm'
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '649606'
      payload_off: '649606off'
      device_class: smoke
      qos: 1
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: "Playroom RF Light Switch"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '84A794'
      payload_off: '84A794off'
    - platform: mqtt
      state_topic: "tele/rfbridge/RESULT"
      name: "Shed Door Sensor"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '986BA9' 
      payload_off: '986BA9off'
    - platorm: mqtt
      state_topic: "shellies/heating2/input/0"
      name: "Manual Floor 1 Switch"
      payload_on: 1
      payload_off: 0
      device_class: heating

homeassistant:
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
