# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies:    
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes   

stream:

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url

template:
  - binary_sensor:
      - name: Sun Up
        state: >
          {{ is_state("sun.sun", "above_horizon") }}
        icon: >
          {% if is_state("binary_sensor.sun_up", "on") %}
            mdi:weather-sunset-up
          {% else %}
            mdi:weather-sunset-down
          {% endif %}
  - sensor:
      - name: Next Sunrise
        state: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon: mdi:weather-sunset-up
      - name: Next Sunset
        state: >
         {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon: mdi:weather-sunset-down
      - name: Number Lights On
        state: >
          {{ dict(states.light|groupby('state'))['on']|length }}
      - name: Adjusted NSPanel temperature
        unit_of_measurement: "°C"
        state: >
          {{ (states('sensor.livingroompanel_analog_temperature1')|float * 0.7755)|round(1, 'common')}}
      - name: Gas Usage
        state_class: measurement
        unit_of_measurement: kW
        device_class: power
        state: >
          {% set kwh_usage = 0 %}
          {% if states('sensor.hotwater_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 10 %}
          {%- endif %}
          {% if states('sensor.downstairs_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 13 %}
          {%- endif %}
          {% if states('sensor.heating2_channel_1_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 10 %}
          {%- endif %}
          {% if states('sensor.heating2_channel_2_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 8 %}
          {%- endif %}
          {{kwh_usage if kwh_usage < 23 else 23}}

sensor:
  - platform: integration
    source: sensor.gas_usage
    name: gas_used
    method: left
    round: 2

google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
   - camera
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate

timer:
  landing_motion:
    duration: '00:03:00'
  outdoor_motion:
    duration: '00:02:00'
  hotwater_boost:
    duration: '01:00:00'
  heating_boost:
    duration: '01:00:00'
  pantry_light_timer:
    duration: '00:10:00'

 
media_player:
  - platform: androidtv
    name: Philips OLED
    host: 192.168.1.209
  - platform: braviatv
    name: Garden room TV
    host: 192.168.1.224
  - platform: enigma2
    host: 192.168.1.131
    password: !secret vu_password




homeassistant:
  customize: !include customize.yaml

switch: !include switches.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml
climate: !include climate.yaml