# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

python_script:

http:
  use_x_forwarded_for: true
  trusted_proxies:    
    - 172.30.33.0/24

frontend:
  themes: !include_dir_merge_named themes   

stream:

spc:
  api_url: !secret spc_api_url
  ws_url: !secret spc_ws_url

template:
  - binary_sensor:
      - name: Sun Up
        state: >
          {{ is_state("sun.sun", "above_horizon") }}
        icon: >
          {% if is_state("binary_sensor.sun_up", "on") %}
            mdi:weather-sunset-up
          {% else %}
            mdi:weather-sunset-down
          {% endif %}
  - sensor:
      - name: Next Sunrise
        state: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon: mdi:weather-sunset-up
      - name: Next Sunset
        state: >
         {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
        icon: mdi:weather-sunset-down
      - name: Number Lights On
        state: >
          {{ dict(states.light|groupby('state'))['on']|length }}
      - name: Adjusted NSPanel temperature
        unit_of_measurement: "°C"
        state: >
          {{ (states('sensor.livingroompanel_analog_temperature1')|float * 0.7755)|round(1, 'common')}}
      - name: Gas Usage
        state_class: measurement
        unit_of_measurement: kW
        device_class: power
        state: >
          {% set kwh_usage = 0 %}
          {% if states('sensor.hotwater_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 10 %}
          {%- endif %}
          {% if states('sensor.downstairs_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 13 %}
          {%- endif %}
          {% if states('sensor.heating2_channel_1_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 10 %}
          {%- endif %}
          {% if states('sensor.heating2_channel_2_power')|float >0 -%}
            {% set kwh_usage = kwh_usage + 8 %}
          {%- endif %}
          {{kwh_usage if kwh_usage < 23 else 23}}

sensor:
  - platform: integration
    source: sensor.gas_usage
    name: gas_used
    method: left
    round: 2

google_assistant:
 project_id: fruitfield-5db56
 service_account: !include service_account.json
 report_state: true
 exposed_domains:
   - switch
   - light
   - camera
#  entity_config:
#    switch.kitchen:
#      name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
#      aliases:
#        - BRIGHT_LIGHTS
#        - ENTRY_LIGHTS
#    light.living_room:
#      expose: false
#      room: LIVING_ROOM

# Text to speech
tts:
  - platform: google_translate

timer:
  landing_motion:
    duration: '00:03:00'
  outdoor_motion:
    duration: '00:02:00'
  hotwater_boost:
    duration: '01:00:00'
  heating_boost:
    duration: '01:00:00'
  pantry_light_timer:
    duration: '00:10:00'

climate:
  - platform: generic_thermostat
    name: Downstairs (Living Room)
    min_temp: 5
    max_temp: 32
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.downstairs_living_room
    target_sensor: sensor.0x00124b0024ce1bc7_temperature
    target_temp: 7
  - platform: generic_thermostat
    name: Downstairs (Kitchen)
    min_temp: 5
    max_temp: 30
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.downstairs_kitchen
    target_sensor: sensor.kitchen_temperature_temperature
    target_temp: 7
  - platform: generic_thermostat
    name: Upstairs (Study)
    min_temp: 5
    max_temp: 30
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.floor1
    target_sensor: sensor.0x00124b002517def2_temperature
    target_temp: 7
  - platform: generic_thermostat
    name: Upstairs (Master Bedroom)
    min_temp: 5
    max_temp: 30
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "heat"
    heater: switch.floor2
    target_sensor: sensor.master_bedroom_temperature_temperature
    target_temp: 7
 
media_player:
  - platform: androidtv
    name: Philips OLED
    host: 192.168.1.209
  - platform: braviatv
    name: Garden room TV
    host: 192.168.1.224
  - platform: enigma2
    host: 192.168.1.131
    password: !secret vu_password



mqtt:
  binary_sensor:
      - name: 'Landing Motion'
        state_topic: "tele/rfbridge/RESULT"
        value_template: '{{value_json.RfReceived.Data}}'
        payload_on: 'E6BC6E'
        payload_off: 'E6BC6Eoff'
        device_class: motion
        qos: 1
      - name: 'Playroom Motion'
        state_topic: "tele/rfbridge/RESULT"
        value_template: '{{value_json.RfReceived.Data}}'
        payload_on: 'E6AA3E'
        payload_off: 'E6AA3Eoff'
        device_class: motion
        qos: 1  
      
  cover:
    - name: "Back Blind #1"
      command_topic: "cmnd/rfbridge/Backlog0"
      state_topic: "stat/rfbridge/blind1"
      payload_open: >
        RfRaw AA B0 4C 04 08 1374 0262 012C 13B0 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A1A192A19 55;
        RfRaw 0
      payload_close: >
        RfRaw AA B0 4C 04 08 1374 0276 012C 13BA 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A192A1A1A1A192929292929292A192A19 55;
        RfRaw 0
      payload_stop: >
        RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A192929292A19292A192A19 55;
        RfRaw 0
    - name: "Back Blind #2"
      command_topic: "cmnd/rfbridge/Backlog0"
      payload_open:  >
        RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A1A192929 55;
        RfRaw 0
      payload_close: >
        RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1A192929292929292A192929 55;
        RfRaw 0
      payload_stop: >
        RfRaw AA B0 4C 04 08 1374 0262 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A192A1A1A192929292A19292A192929 55;
        RfRaw 0
    - name: "Back Blind #3"
      command_topic: "cmnd/rfbridge/Backlog0"
      payload_open: >
        RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A192A1929 55;
        RfRaw 0
      payload_close: >
        RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292929292929292A1929 55;
        RfRaw 0
      payload_stop: >        
        RfRaw AA B0 4C 04 08 1374 026C 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A1A1A192929292A1929292A1929 55;        
        RfRaw 0
    - name: "Back Blind #4"
      command_topic: "cmnd/rfbridge/Backlog0"
      payload_open: >
        RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A192A1A1929 55;
        RfRaw 0
      payload_close: >
        RfRaw AA B0 4C 04 08 1374 026C 0118 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292A1A1A1A1A1A1A1929 55;
        RfRaw 0
      payload_stop: >
        RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A19292929292A1A1A1A1929 55;
        RfRaw 0
    - name: "Sitting Room Blind"
      command_topic: "cmnd/rfbridge/Backlog0"
      payload_open: >
        RfRaw AA B0 4C 04 08 136A 026C 012C 13C4 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A192A1A1A1929 55;
        RfRaw 0
      payload_close: >
        RfRaw AA B0 4C 04 08 137E 0262 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292A1A1A1A192A1A1929 55;
        RfRaw 0
      payload_stop: >
        RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A19292929292A192A1A1929 55;
        RfRaw 0

homeassistant:
  customize: !include customize.yaml

switch: !include switches.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
