---
- platform: group
  name: "Kitchen Lights"
  entities:
    - light.kitchen_corner_2
    - light.pantry
- platform: group
  name: Security Lights
  entities:
    - light.front_door_light
    - light.side_door_security
    - light.back_door_security
  all: true
- platform: group
  name: Living Room Lights
  entities:
    - light.livingroomlight_1
    - light.livingroomlight_2
- platform: group
  name: Outdoor Lights
  entities:
    - light.front_door_light
    - light.veranda
    - light.pathlights
    - light.back_door_porch
- platform: group
  name: Study lights
  entities:
    - light.study
    - light.shellyrgbw2_a8e75d