---
binary_sensor:
    - name: 'Landing Motion'
      state_topic: "tele/rfbridge/RESULT"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: 'E6BC6E'
      payload_off: 'E6BC6Eoff'
      device_class: motion
      qos: 1
    - name: 'Hotpress RF Switch'
      state_topic: "tele/rfbridge/RESULT"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: '84A794'
      payload_off: '84A794off'
    - name: 'Playroom Motion'
      state_topic: "tele/rfbridge/RESULT"
      value_template: '{{value_json.RfReceived.Data}}'
      payload_on: 'E6AA3E'
      payload_off: 'E6AA3Eoff'
      device_class: motion
      qos: 1  
    - name: 'Pantry Door'
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x62BB']['ZoneStatusChange'] }}"
      device_class: door
      payload_on: 1
      payload_off: 0 
    - name: 'Kitchen Door'
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x6050']['ZoneStatusChange'] }}"
      device_class: door
      payload_on: 1
      payload_off: 0 
    - name: 'Living Room Motion'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      payload_on: 1
      payload_off: 0
      value_template: "{{ value_json['ZbReceived']['0x1C57']['ZoneStatusChange'] }}"
      device_class: motion
    - name: 'Pantry Motion'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      payload_on: 1
      payload_off: 0
      value_template: "{{ value_json['ZbReceived']['0xEA86']['ZoneStatusChange'] }}"
      device_class: motion
sensor:
    - name: 'Office Temperature'
      unit_of_measurement: '째C'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xACC4']['Temperature'] }}"
      device_class: temperature
    - name: 'Office Humidity'
      unit_of_measurement: "%"
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0xACC4']['Humidity'] }}"
      device_class: humidity
    - name: 'Master Bedroom Temperature'
      unit_of_measurement: '째C'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x91A8']['Temperature'] }}"
      device_class: temperature
    - name: 'Master Bedroom Humidity'
      unit_of_measurement: "%"
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x91A8']['Humidity'] }}"
      device_class: humidity
    - name: 'Kitchen Temperature'
      unit_of_measurement: '째C'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x0807']['Temperature'] }}"
      device_class: temperature
    - name: 'Kitchen Humidity'
      unit_of_measurement: "%"
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x0807']['Humidity'] }}"
      device_class: humidity
    - name: 'Living Room Temperature'
      unit_of_measurement: '째C'
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x70A8']['Temperature'] }}"
      device_class: temperature
    - name: 'Living Room Humidity'
      unit_of_measurement: "%"
      availability_topic: "tele/zbbridge/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      state_topic: "tele/zbbridge/SENSOR"
      value_template: "{{ value_json['ZbReceived']['0x70A8']['Humidity'] }}"
      device_class: humidity
switch:
   - unique_id: kitchen_corner
     name: "Kitchen Corner"
     availability_topic: "tele/zbbridge/LWT"
     payload_available: "Online"
     payload_not_available: "Offline"
     command_topic: "cmnd/zbbridge/ZbSend"
     payload_on: '{"device":"0xEBD3","send":{"Power":"On"} }' 
     payload_off: '{"device":"0xEBD3","send":{"Power":"Off"} }'  
     qos: 1
     retain: false
     state_on: '1'
     state_off: '0'
     state_topic: "tele/zbbridge/SENSOR"
     value_template: "{{ value_json['ZbReceived']['0xEBD3']['Power'] }}"
     icon: mdi:floor-lamp
   - unique_id: office_socket
     name: "Office Socket"
     availability_topic: "tele/zbbridge/LWT"
     payload_available: "Online"
     payload_not_available: "Offline"
     command_topic: "cmnd/zbbridge/ZbSend"
     payload_on: '{"device":"0x280F8","send":{"Power":"On"} }' 
     payload_off: '{"device":"0x80F8","send":{"Power":"Off"} }'  
     qos: 1
     retain: false
     state_on: '1'
     state_off: '0'
     state_topic: "tele/zbbridge/SENSOR"
     value_template: "{{ value_json['ZbReceived']['Office Socket']['Power'] }}"
     icon: mdi:power-socket-uk
   - unique_id: extra_socket
     name: "Extra Socket"
     availability_topic: "tele/zbbridge/LWT"
     payload_available: "Online"
     payload_not_available: "Offline"
     command_topic: "cmnd/zbbridge/ZbSend"
     payload_on: '{"device":"0xAECC","send":{"Power":"On"} }' 
     payload_off: '{"device":"0xAECC","send":{"Power":"Off"} }'  
     qos: 1
     retain: false
     state_on: '1'
     state_off: '0'
     state_topic: "tele/zbbridge/SENSOR"
     value_template: "{{ value_json['ZbReceived']['Extra Socket']['Power'] }}"
     icon: mdi:power-socket-uk
light:
  - name: "Davins Light"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    command_topic: "cmnd/zbbridge/ZbSend"
    payload_on: '{"device":"0x1102","send":{"power":1}}' 
    payload_off: '{"device":"0x1102","send":{"power":0}}'  
    qos: 1
    retain: false
    state_topic: "tele/zbbridge/SENSOR"
    state_value_template: "{{ value_json['ZbReceived']['0x1102']['Power'] }}"
    optimistic: false
button:
  - unique_id: z2t_enable_join
    name: "Zigbee2Tasmota enable join"
    command_topic: "cmnd/zbbridge/ZbPermitJoin" 
    payload_press: "1"
    availability_topic: "tele/zbbridge/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    entity_category: "config"
    device_class: "restart"
cover:
  - name: "Back Blind #1"
    command_topic: "cmnd/rfbridge/Backlog0"
    state_topic: "stat/rfbridge/blind1"
    payload_open: >
      RfRaw AA B0 4C 04 08 1374 0262 012C 13B0 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A1A192A19 55;
      RfRaw 0
    payload_close: >
      RfRaw AA B0 4C 04 08 1374 0276 012C 13BA 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A192A1A1A1A192929292929292A192A19 55;
      RfRaw 0
    payload_stop: >
      RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A192929292A19292A192A19 55;
      RfRaw 0
  - name: "Back Blind #2"
    command_topic: "cmnd/rfbridge/Backlog0"
    payload_open:  >
      RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A1A192929 55;
      RfRaw 0
    payload_close: >
      RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1A192929292929292A192929 55;
      RfRaw 0
    payload_stop: >
      RfRaw AA B0 4C 04 08 1374 0262 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A192A1A1A192929292A19292A192929 55;
      RfRaw 0
  - name: "Back Blind #3"
    command_topic: "cmnd/rfbridge/Backlog0"
    payload_open: >
      RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A1A192A1929 55;
      RfRaw 0
    payload_close: >
      RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292929292929292A1929 55;
      RfRaw 0
    payload_stop: >        
      RfRaw AA B0 4C 04 08 1374 026C 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A1A1A192929292A1929292A1929 55;        
      RfRaw 0
  - name: "Back Blind #4"
    command_topic: "cmnd/rfbridge/Backlog0"
    payload_open: >
      RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A1A192A1A1929 55;
      RfRaw 0
    payload_close: >
      RfRaw AA B0 4C 04 08 1374 026C 0118 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292A1A1A1A1A1A1A1929 55;
      RfRaw 0
    payload_stop: >
      RfRaw AA B0 4C 04 08 1374 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A19292929292A1A1A1A1929 55;
      RfRaw 0
  - name: "Sitting Room Blind"
    command_topic: "cmnd/rfbridge/Backlog0"
    payload_open: >
      RfRaw AA B0 4C 04 08 136A 026C 012C 13C4 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A192A192929292A192A1A1A1929 55;
      RfRaw 0
    payload_close: >
      RfRaw AA B0 4C 04 08 137E 0262 0122 137E 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A1A19292A1A1A1A192A1A1929 55;
      RfRaw 0
    payload_stop: >
      RfRaw AA B0 4C 04 08 137E 026C 0122 1388 38192A192A19292A1A192A192A1A1A1A19292A1A192A19292A1A192929292929292A1A1A192A1A1A1A1A1A1A1A1A1A1A1A1A1A192A1A1A19292929292A192A1A1929 55;
      RfRaw 0
