---
- platform: wake_on_lan
  mac: a4:83:e7:97:53:c0

- platform: template
  switches:
    security_lights:
      friendly_name: "Outdoor Lights"
      value_template: "{{ is_state('light.utility_outside', 'on') }}"
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.utility_outside
          entity_id: light.front_door_light
      turn_off:
        service: light.turn_off
        data:
          entity_id: >
            {% if is_state('input_boolean.house_light_up_time', 'on') %}
            entity_id: light.utility_outside
            {% else %}
            entity_id: light.utility_outside
            entity_id: light.front_door_light
            {% endif %}
          
