---
- platform: wake_on_lan
  mac: a4:83:e7:97:53:c0

- platform: template
  switches:
    security_lights:
      friendly_name: "Security Lights"
      value_template: "{{ is_state('light.utility_outside', 'on') }}"
      turn_on:
        service: light.turn_on
        target:
          entity_id:
            - light.utility_outside
            - light.front_door_light
      turn_off:
        service: light.turn_off
        target:
          entity_id: >-
            {% if is_state('input_boolean.house_light_up_time', 'off') %}
            - light.utility_outside
            - light.front_door_light
            {% else %}
            - light.utility_outside
            {% endif %}
